#!/usr/bin/env python3
"""Open one PR per changed ticket file, then a final PR for index.md.

Workflow:
1. Regenerate the tracker into a staging directory (without touching the repo).
2. Compare staging vs. the live `requests/` and `index.md`.
3. For each added / modified / deleted ticket: branch off the latest base,
   apply only that file change, push, open a PR, squash-merge.
4. If `index.md` changed, do the same for it last.

This script assumes:
- It is run from the repo root.
- `gh` is authenticated (env var `GH_TOKEN` or `GITHUB_TOKEN`).
- The base branch (default: GITHUB_REF_NAME or `main`) exists on `origin`.
"""
from __future__ import annotations

import argparse
import filecmp
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

REQUEST_ID_RE = re.compile(r"FB\d+")


@dataclass
class Settings:
    base: str
    run_id: str
    server_url: str
    repo: str
    requests_dir: Path
    index_path: Path
    source: str | None


def run(cmd: list[str], *, check: bool = True, capture: bool = False) -> str:
    print(f"$ {' '.join(cmd)}", file=sys.stderr)
    try:
        result = subprocess.run(
            cmd,
            check=check,
            text=True,
            stdout=subprocess.PIPE if capture else None,
            stderr=subprocess.PIPE if capture else None,
        )
    except subprocess.CalledProcessError as e:
        # Surface captured output before re-raising so workflow logs show
        # the underlying tool's error message.
        if e.stdout:
            sys.stderr.write(e.stdout)
        if e.stderr:
            sys.stderr.write(e.stderr)
        raise
    if capture:
        if result.stderr:
            sys.stderr.write(result.stderr)
        return (result.stdout or "").strip()
    return ""


def request_id_from_filename(name: str) -> str:
    m = REQUEST_ID_RE.search(name)
    return m.group(0) if m else name.removesuffix(".md")


def list_changes(staging_requests: Path, live_requests: Path) -> tuple[list[str], list[str], list[str]]:
    """Return (added, modified, deleted) ticket filenames."""
    staging_files = {p.name for p in staging_requests.iterdir() if p.is_file()}
    live_files = {p.name for p in live_requests.iterdir() if p.is_file()} if live_requests.exists() else set()

    added = sorted(staging_files - live_files)
    deleted = sorted(live_files - staging_files)
    modified = sorted(
        name for name in staging_files & live_files
        if not filecmp.cmp(staging_requests / name, live_requests / name, shallow=False)
    )
    return added, modified, deleted


def reset_to_remote_base(branch: str, base: str) -> None:
    run(["git", "fetch", "origin", base])
    run(["git", "checkout", "-B", branch, f"origin/{base}"])


def push_branch(branch: str) -> None:
    run(["git", "push", "--set-upstream", "origin", branch])


def open_and_merge_pr(*, base: str, branch: str, title: str, body: str) -> None:
    pr_url = run(
        ["gh", "pr", "create", "--base", base, "--head", branch, "--title", title, "--body", body],
        capture=True,
    )
    print(f"Opened PR: {pr_url}", file=sys.stderr)
    run(["gh", "pr", "merge", pr_url, "--squash", "--delete-branch"])


def commit_one_path(path: Path, message: str) -> None:
    run(["git", "add", "--", str(path)])
    if path.exists():
        # nothing more to do
        pass
    run(["git", "commit", "-m", message])


def commit_removal(path: Path, message: str) -> None:
    run(["git", "rm", "--", str(path)])
    run(["git", "commit", "-m", message])


def make_pr_body(s: Settings, kind: str, target: str) -> str:
    run_url = f"{s.server_url}/{s.repo}/actions/runs/{s.run_id}"
    return (
        f"Automated {kind} for `{target}`.\n\n"
        f"Source: <https://developer.apple.com/file/?file=interoperability-request-tracker>\n"
        f"Generated by run [{s.run_id}]({run_url}).\n"
    )


def sync_ticket_added_or_modified(s: Settings, staging_requests: Path, name: str, *, added: bool) -> None:
    fb = request_id_from_filename(name)
    verb = "add" if added else "update"
    branch = f"auto/ticket-{verb}-{fb}-{s.run_id}"
    title = f"ticket: {verb} {fb}"
    body = make_pr_body(s, f"ticket {verb}", name)

    reset_to_remote_base(branch, s.base)
    s.requests_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(staging_requests / name, s.requests_dir / name)
    target = s.requests_dir / name
    run(["git", "add", "--", str(target)])
    run(["git", "commit", "-m", title])
    push_branch(branch)
    open_and_merge_pr(base=s.base, branch=branch, title=title, body=body)


def sync_ticket_deleted(s: Settings, name: str) -> None:
    fb = request_id_from_filename(name)
    branch = f"auto/ticket-remove-{fb}-{s.run_id}"
    title = f"ticket: remove {fb}"
    body = make_pr_body(s, "ticket removal", name)

    reset_to_remote_base(branch, s.base)
    target = s.requests_dir / name
    if target.exists():
        commit_removal(target, title)
    else:
        # Already gone on main — skip.
        print(f"Skipping {name}: not present on base", file=sys.stderr)
        return
    push_branch(branch)
    open_and_merge_pr(base=s.base, branch=branch, title=title, body=body)


def sync_index(s: Settings, staging_index: Path) -> None:
    branch = f"auto/refresh-index-{s.run_id}"
    title = "chore: refresh tracker index"
    body = make_pr_body(s, "index refresh", s.index_path.name)

    reset_to_remote_base(branch, s.base)
    # Compare again post-reset; if index already matches, no-op.
    if s.index_path.exists() and filecmp.cmp(staging_index, s.index_path, shallow=False):
        print("Index already up-to-date on base; skipping.", file=sys.stderr)
        return
    shutil.copy2(staging_index, s.index_path)
    run(["git", "add", "--", str(s.index_path)])
    run(["git", "commit", "-m", title])
    push_branch(branch)
    open_and_merge_pr(base=s.base, branch=branch, title=title, body=body)


def configure_git_identity() -> None:
    run(["git", "config", "user.name", "github-actions[bot]"])
    run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=None,
                        help="PDF source passed through to update_tracker.py")
    parser.add_argument("--base", default=os.environ.get("GITHUB_REF_NAME", "main"))
    parser.add_argument("--requests-dir", default="requests")
    parser.add_argument("--index", default="index.md")
    args = parser.parse_args(argv)

    s = Settings(
        base=args.base,
        run_id=os.environ.get("GITHUB_RUN_ID", "local"),
        server_url=os.environ.get("GITHUB_SERVER_URL", "https://github.com"),
        repo=os.environ.get("GITHUB_REPOSITORY", "local/local"),
        requests_dir=Path(args.requests_dir),
        index_path=Path(args.index),
        source=args.source,
    )

    with tempfile.TemporaryDirectory(prefix="tracker-staging-") as tmpdir:
        staging = Path(tmpdir)
        staging_requests = staging / "requests"
        staging_index = staging / "index.md"

        gen_cmd = [
            sys.executable, "scripts/update_tracker.py",
            "--out", str(staging_requests),
            "--index", str(staging_index),
        ]
        if args.source:
            gen_cmd += ["--source", args.source]
        run(gen_cmd)

        added, modified, deleted = list_changes(staging_requests, s.requests_dir)
        index_changed = (
            not s.index_path.exists()
            or not filecmp.cmp(staging_index, s.index_path, shallow=False)
        )

        if not (added or modified or deleted or index_changed):
            print("No changes detected.", file=sys.stderr)
            return 0

        print(
            f"Changes — added: {len(added)}, modified: {len(modified)}, "
            f"deleted: {len(deleted)}, index_changed: {index_changed}",
            file=sys.stderr,
        )

        configure_git_identity()

        for name in added:
            sync_ticket_added_or_modified(s, staging_requests, name, added=True)
        for name in modified:
            sync_ticket_added_or_modified(s, staging_requests, name, added=False)
        for name in deleted:
            sync_ticket_deleted(s, name)
        if index_changed:
            sync_index(s, staging_index)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
